// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: profiles.sql

package pg

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (role, firstname, lastname, dob, bio, avatar)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, deleted_at, role, firstname, lastname, dob, bio, avatar
`

type CreateProfileParams struct {
	Role      UserRole
	Firstname sql.NullString
	Lastname  sql.NullString
	Dob       time.Time
	Bio       sql.NullString
	Avatar    sql.NullString
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.Role,
		arg.Firstname,
		arg.Lastname,
		arg.Dob,
		arg.Bio,
		arg.Avatar,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Role,
		&i.Firstname,
		&i.Lastname,
		&i.Dob,
		&i.Bio,
		&i.Avatar,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT p.id, p.created_at, p.updated_at, p.deleted_at, p.role, p.firstname, p.lastname, p.dob, p.bio, p.avatar
FROM profiles p
JOIN user_profiles up ON p.id = up.profile_id
JOIN users u ON up.user_id = u.id
WHERE u.id = $1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Role,
		&i.Firstname,
		&i.Lastname,
		&i.Dob,
		&i.Bio,
		&i.Avatar,
	)
	return i, err
}

const getProfilesByUserIDs = `-- name: GetProfilesByUserIDs :many
SELECT p.id, p.created_at, p.updated_at, p.deleted_at, p.role, p.firstname, p.lastname, p.dob, p.bio, p.avatar
FROM profiles p
JOIN user_profiles up ON p.id = up.profile_id
JOIN users u ON up.user_id = u.id
WHERE u.id = ANY($1::UUID[])
`

func (q *Queries) GetProfilesByUserIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, getProfilesByUserIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
			&i.Firstname,
			&i.Lastname,
			&i.Dob,
			&i.Bio,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
