// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: icons.sql

package pg

import (
	"context"
)

const createIcon = `-- name: CreateIcon :one
INSERT INTO icons (name, url, type)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, deleted_at, name, url, type
`

type CreateIconParams struct {
	Name string  `json:"name"`
	Url  string  `json:"url"`
	Type *string `json:"type"`
}

func (q *Queries) CreateIcon(ctx context.Context, arg CreateIconParams) (Icon, error) {
	row := q.db.QueryRow(ctx, createIcon, arg.Name, arg.Url, arg.Type)
	var i Icon
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Url,
		&i.Type,
	)
	return i, err
}
